from __future__ import annotations

import time

import blobfile as bf
import chz
import structlog
from nanoeval.solvers.computer_tasks.code_execution_interface import ComputerInterface
from paperbench.nano.structs import AgentOutput
from paperbench.nano.task import PBTask
from paperbench.solvers.basicagent.prompts.templates import get_system_message
from paperbench.solvers.basicagent.solver import BasicAgentSolver as LibraryBasicAgentSolver
from paperbench.solvers.basicagent.utils import get_instructions
from paperbench.solvers.utils import check_for_existing_run, sanity_check_docker
from typing_extensions import override

logger = structlog.stdlib.get_logger(component=__name__)

STRICT_REPLICATION_NOTE = """
IMPORTANT EXPERIMENT REPLICATION REQUIREMENT
---
Make sure to *fully replicate the paper's experiments*. When there is an experiment
in the paper, do *NOT* run a small toy task and pass it off as the full experiment.
If runtime forces a smaller smoke test, clearly label it as a smoke test and keep
the full experiment path as the default reproduce.sh behavior. Do NOT fake results
or pass off proxies as replications; rerun the paper experiments exactly whenever
claiming reproduction credit.

Artifact provenance requirement:
Do not commit final result CSVs, plots, tables, JSON summaries, checkpoints, or
metrics that were not generated by the submitted code. The final reproduce.sh run
must create all claimed result artifacts from raw inputs, configs, seeds, training,
sampling, and evaluation code. If you include example or smoke-test outputs, mark
them clearly as non-final and never use them as evidence for paper reproduction.
"""


@chz.chz
class BasicAgentSolver(LibraryBasicAgentSolver):
    """Baseline editable BasicAgent for PaperBench-score hill climbing."""

    extra_instructions: str = STRICT_REPLICATION_NOTE

    @override
    def shortname(self) -> str:
        return "mh_basicagent"

    @override
    async def _run_agent(self, computer: ComputerInterface, task: PBTask) -> AgentOutput:
        existing = await check_for_existing_run(task)
        if existing:
            return existing

        await sanity_check_docker(computer)
        start_time = time.time()
        instructions = await get_instructions(computer, task, self.iterative_agent, self.time_limit)
        instructions = f"{instructions}\n\n{self.extra_instructions.strip()}\n"
        system_message = get_system_message(self.iterative_agent, task.judge.code_only)
        await self._execute_agent_and_periodically_upload_logs(
            computer=computer,
            task=task,
            prompt=[
                {"role": "system", "content": system_message},
                {"role": "user", "content": instructions},
            ],
        )

        logger.info(
            f"Agent `{self.shortname()}` finished running for `{task.question_id}.{task.attempt_id}`!",
            destinations=["group", "run"],
            _print=True,
        )
        return AgentOutput(
            run_id=task.run_id,
            time_start=start_time,
            time_end=time.time(),
            error_msg=None,
            runtime_in_seconds=time.time() - start_time,
            status_exists=bf.exists(bf.join(task.run_dir, "status.json")),
        )
